### ISSUE TITLE
支付后不回调

### ISSUE THREAD

**Issue by dsmnoi** [52fancy/whmcs-yzpay#1]
支付后不回调

另外打不开
https://github.com/52fancy/whmcs-yzpay/wiki/%E6%9C%89%E8%B5%9E%E4%BA%91%E4%BA%A4%E6%98%93API%E5%BC%80%E9%80%9A%E6%95%99%E7%A8%8B

**Comment by 52fancy** [comment]
之前把wiki删掉了，现在重新补上了，你看一下吧

**Comment by SCNU-WH** [comment]
现在支付后又不回调了，麻烦看下。
