### ISSUE TITLE
感谢大佬，现在有赞更新了，请问流程怎样操作呢？

### ISSUE THREAD

**Issue by ScriptElite** [52fancy/whmcs-yzpay#4]
感谢大佬，现在有赞更新了，请问流程怎样操作呢？

授权店铺:
选择本帐号下的店铺 处查询不到店铺，不能点击下一步进行授权。

**Comment by 52fancy** [comment]
现在微小店的方法已经不能用了，想用就得付费开通店铺了。
可以加群咨询一下
